### ISSUE TITLE
FLIMfit 5.0.3 fails to show fit results in Images tab

### ISSUE THREAD

**Issue by ilyaradko** [flimfit/FLIMfit#330] opened 2017-08-04 09:57 UTC
Fit process goes without problem. However, when I try to show the results in the Images tab (at the moment I set a checkbox on the right for any of the fitting parameters), FLIMfit gives the following error:

`Error using insertText>populateGlyphBuffer_sim (line 778)`
`Undefined function 'visionPopulateGlyphBuffer' for input arguments of type 'uint8'.`
`Error in insertText (line 139)`
`Error in display_flim (line 142)`
`Error in flim_fit_plot_controller/plot_figure2 (line 58)`
`Error in flim_fit_plot_controller/update_plots (line 95)`
`Error in flim_fit_plot_controller/fit_display_update (line 88)`
`Error in flim_fit_observer/fit_display_update_evt (line 53)`
`Error in flim_fit_observer>@(varargin)obj.fit_display_update_evt(varargin{:}) (line 40)`
`Error in escaped_callback (line 7)`
`Error in flim_fit_observer>@(~,~)escaped_callback(@obj.fit_display_update_evt) (line 40)`
`Error in flim_fit_controller/plot_select_update (line 488)`
`Error in flim_fit_controller>@(varargin)obj.plot_select_update(varargin{:}) (line 158)`
`Error in escaped_callback (line 7)`
`Error in flim_fit_controller>@(~,~)escaped_callback(@obj.plot_select_update) (line 158)`

This happens with any processed data. Works fine with previous versions of FLIMfit.
Also noticed that on start of FLIMfit, it gives quite a number of warnings in the console window (though, no errors) - this was not the case with previous versions.

Is it possible (as a temporary measure) to save the fitting data without showing them in Images tab?

**Comment by imunro** [comment] 2017-08-04 10:19
Thanks for letting us know and our apologies for missing that in our testing. Cam I ask which OS you are using please and what sort of files? I remember that you have been working with picoquant .bin files in the past.

**Comment by ilyaradko** [comment] 2017-08-04 10:22
Yes, I am using picoquant .bin files and Windows 7 Enterprise SP1, 64bit.

**Comment by imunro** [comment] 2017-08-04 10:26
Thanks. I'll investigate and get back to you.

**Comment by imunro** [comment] 2017-08-04 13:08
Hi Ilya I can see a lot of warnings as you say  - can I check attached screenshot match what you're seeing?.
But I can't seem to replicate the issue with the .bin files that I have available . Could you possibly send me the problematic file/s to try.

<img width="708" alt="screen shot 2017-08-04 at 14 03 29" src="https://user-images.githubusercontent.com/1183110/28969810-071cf318-791e-11e7-856f-d64f9d568256.png">

**Comment by ilyaradko** [comment] 2017-08-04 13:38
Yes, I see exactly the same warnings.
I uploaded two files on https://www.openmicroscopy.org/qa2/ under the case ID 17829 - a data file and an IRF function. Hope you can reproduce the issue.

**Comment by imunro** [comment] 2017-08-04 14:44
Thanks Ilya

**Comment by imunro** [comment] 2017-08-04 17:10
@ilyaradko I've tried fitting your data using 5.0.3 on Windows Server 2012 R2 ( the nearest OS to yours to which I have access at the moment) and I couldn't replicate your issues. The images in the tab didn't look that great, for example the colourbar was the same size as the image but I couldn't see any major issues.  Is it ok if I  send your data  to my colleague @seanwarren in case he has access to a more appropriate system?

**Comment by ilyaradko** [comment] 2017-08-04 17:29
Hi @imunro, Sure, you are welcome to send the files to @seanwarren. The data itself do not have much meaning - it is just a dummy file I use for testing purposes because of its small size. But I observe exactly the same problem with any real data file I have.

**Comment by imunro** [comment] 2017-10-11 09:28
Hi @ilyaradko as I'm still unable to reproduce this I'm going to close this for now. If the problem is still present in the new  Version  5.1 (hopefully to be released very shortly) please re-open this issue,

**Closed by imunro** 2017-10-11 09:28 UTC
